# .air.toml

# Watch these directories and files
[watch]
  dirs = ["."]
  extensions = [".go"]
  exclude_dir = ["vendor", "tmp", "bin", "docs"]

# Build config
[build]
  bin = "tmp/main"               # Binary output location
  cmd = "go build -o tmp/main ." # Build command
  delay = 1000                   # Delay rebuild in ms
  exclude = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "build.log"

# Run config
[run]
  cmd = "./tmp/main"             # Command to run
  grace_time = 500               # Wait before killing process
  kill_signal = "SIGINT"

# Logging
[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
