name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ vars.DOCKERHUB_USERNAME }}    # Organization variable
      DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}    # Organization secret
      IMAGE_NAME: order-service
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
